openapi: 3.0.0
info:
  title: Store-API
  contact: {}
  version: '1.0'
servers:
- url: http://localhost:4000/api/v1
  variables: {}
paths:
  /products:
    get:
      tags:
      - Store- Products
      summary: Get All Products
      operationId: GetAllProducts
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /products/static:
    get:
      tags:
      - Store- Products
      summary: GetAllProductsStatic
      operationId: GetAllProductsStatic
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
tags:
- name: Store- Products
  description: ''